meta_product_name: "Footprint"
meta_title: "Footprint - Améliorez votre empreinte carbonne"
meta_description: "Footprint vous permet de scanner un ticket de caisse et d'obtenir une note relative à l'impact environnemental de vos achats du quotidien "
meta_image: "cover.jpg" # should exist in `app/assets/images/`
